framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus: ~
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    delete_after_ack: true
        routing:
            App\Application\Query\AsyncQuery: async
            App\Application\Event\AsyncEvent: async
            App\Application\Command\AsyncCommand: async
